//! Reading table data. Every column is fetched as `text` so one value model covers arrays, jsonb,
//! ranges, bytea, numerics and custom types alike.
//!
//! **Large values never enter the grid.** For columns that can hold big values (json, jsonb, text,
//! bytea, ...) the query uses `pg_column_size`, which reads the stored size without detoasting, to
//! skip the expensive cast/serialisation of anything above [`INLINE_STORED_LIMIT`]. Those cells come
//! back as [`Cell::Large`] and are only loaded on request via [`fetch_cell`], under a byte cap.

use crate::error::{ErrorKind, UserFacingError};
use crate::session::Session;
use crate::sql::{quote_ident, quote_qualified};

pub const DEFAULT_PAGE_SIZE: usize = 500;

/// Values whose *stored* size (possibly compressed) exceeds this are not fetched into the grid.
pub const INLINE_STORED_LIMIT: usize = 8 * 1024;
/// Compressed values can expand many times over as text, so anything that still arrives above this
/// is demoted to [`Cell::Large`] and its text dropped.
pub const MAX_INLINE_TEXT_BYTES: usize = 64 * 1024;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Identity {
    #[default]
    None,
    /// `GENERATED ALWAYS AS IDENTITY`: cannot be written.
    Always,
    /// `GENERATED BY DEFAULT AS IDENTITY`: may be written, defaults otherwise.
    ByDefault,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Column {
    pub name: String,
    /// As displayed by `format_type`, e.g. `numeric(10,2)` or `text[]`.
    pub type_name: String,
    pub not_null: bool,
    pub is_primary_key: bool,
    pub identity: Identity,
    /// `GENERATED ALWAYS AS (expr) STORED`: computed by the server, cannot be written.
    pub generated: bool,
    pub has_default: bool,
}

impl Column {
    /// Whether a value can be written to this column (false for generated / always-identity).
    pub fn is_writable(&self) -> bool {
        !self.generated && self.identity != Identity::Always
    }

    /// Whether values of this type may be large enough to need the guarded fetch.
    pub fn is_large_capable(&self) -> bool {
        !is_bounded_type(&self.type_name)
    }
}

/// Types whose values are always small. Everything else (json, jsonb, text, varchar, bytea, xml,
/// arrays, ranges, custom and domain types) goes through the size guard.
pub fn is_bounded_type(type_name: &str) -> bool {
    if type_name.ends_with("[]") {
        return false;
    }
    let base = type_name.split('(').next().unwrap_or("").trim();
    matches!(
        base,
        "smallint" | "integer" | "bigint" | "real" | "double precision" | "numeric" | "decimal"
            | "boolean" | "date" | "money" | "uuid" | "inet" | "cidr" | "macaddr" | "macaddr8"
            | "oid" | "\"char\"" | "character" | "bit" | "name"
    ) || base.starts_with("timestamp")
        || base.starts_with("time ")
        || base == "time"
        || base.starts_with("interval")
}

/// One grid cell. Only [`Cell::Text`] carries data; large values are represented by their size.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Cell {
    Null,
    Text(String),
    /// Not loaded. `stored_bytes` is the on-disk (possibly compressed) size.
    Large { stored_bytes: i64 },
}

impl Cell {
    pub fn as_text(&self) -> Option<&str> {
        match self {
            Cell::Text(t) => Some(t),
            _ => None,
        }
    }

    pub fn is_null(&self) -> bool {
        matches!(self, Cell::Null)
    }

    pub fn is_large(&self) -> bool {
        matches!(self, Cell::Large { .. })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TablePage {
    pub columns: Vec<Column>,
    pub rows: Vec<Vec<Cell>>,
    pub offset: usize,
    /// True when at least one more row exists after this page.
    pub has_more: bool,
}

pub async fn table_columns(
    session: &Session,
    schema: &str,
    table: &str,
) -> Result<Vec<Column>, UserFacingError> {
    let target = session.info().endpoint.clone();
    let qualified = quote_qualified(schema, table);
    let rows = session
        .client()
        .query(
            "SELECT a.attname::text, format_type(a.atttypid, a.atttypmod), a.attnotnull, \
                    EXISTS (SELECT 1 FROM pg_index i \
                            WHERE i.indrelid = a.attrelid AND i.indisprimary \
                              AND a.attnum = ANY (i.indkey)), \
                    a.attidentity::text, a.attgenerated::text, a.atthasdef \
             FROM pg_attribute a \
             WHERE a.attrelid = to_regclass($1) AND a.attnum > 0 AND NOT a.attisdropped \
             ORDER BY a.attnum",
            &[&qualified],
        )
        .await
        .map_err(|e| UserFacingError::from_pg(&e, Some(&target)))?;
    if rows.is_empty() {
        return Err(UserFacingError {
            kind: ErrorKind::ObjectNotFound,
            title: "Table not found".into(),
            detail: format!("{schema}.{table} does not exist any more (it may have been dropped or renamed)."),
            hint: Some("Refresh the navigator.".into()),
            sqlstate: None,
            position: None,
            retryable: false,
            raw: String::new(),
        });
    }
    Ok(rows
        .iter()
        .map(|r| {
            let identity: String = r.get(4);
            let generated: String = r.get(5);
            Column {
                name: r.get(0),
                type_name: r.get(1),
                not_null: r.get(2),
                is_primary_key: r.get(3),
                identity: match identity.as_str() {
                    "a" => Identity::Always,
                    "d" => Identity::ByDefault,
                    _ => Identity::None,
                },
                generated: !generated.is_empty(),
                has_default: r.get(6),
            }
        })
        .collect())
}

/// What the current user may do to a table, and what kind of relation it is.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Access {
    pub select: bool,
    pub insert: bool,
    pub update: bool,
    pub delete: bool,
    /// `pg_class.relkind`: `r` table, `p` partitioned table, `v` view, `m` matview, `f` foreign.
    pub relkind: String,
}

impl Access {
    pub fn is_plain_table(&self) -> bool {
        matches!(self.relkind.as_str(), "r" | "p")
    }
}

pub async fn table_access(session: &Session, schema: &str, table: &str) -> Result<Access, UserFacingError> {
    let target = session.info().endpoint.clone();
    let qualified = quote_qualified(schema, table);
    let rows = session
        .client()
        .query(
            "SELECT has_table_privilege(c.oid, 'SELECT'), has_table_privilege(c.oid, 'INSERT'), \
                    has_table_privilege(c.oid, 'UPDATE'), has_table_privilege(c.oid, 'DELETE'), \
                    c.relkind::text \
             FROM pg_class c WHERE c.oid = to_regclass($1)",
            &[&qualified],
        )
        .await
        .map_err(|e| UserFacingError::from_pg(&e, Some(&target)))?;
    let Some(r) = rows.first() else { return Ok(Access::default()) };
    Ok(Access { select: r.get(0), insert: r.get(1), update: r.get(2), delete: r.get(3), relkind: r.get(4) })
}

/// Alias for the table in generated queries. Every column reference is qualified with it so that
/// `ORDER BY` can never resolve to an *output* column of the same name: `SELECT "id"::text ...
/// ORDER BY "id"` would sort by the text form ("1", "10", "100", ...), not the integer.
const TABLE_ALIAS: &str = "pgb_t";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sort {
    pub column: String,
    pub descending: bool,
}

/// Which rows to show.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum Filter {
    #[default]
    None,
    /// A SQL boolean expression typed by the user (like DataGrip's filter bar). It runs with the
    /// user's own privileges, exactly as if typed in the SQL console.
    Raw(String),
    /// `column = value` for each pair, ANDed. Used when following a foreign key. Values are bound
    /// parameters cast to the column type, so they use indexes and cannot inject SQL.
    Match(Vec<(String, String)>),
}

impl Filter {
    pub fn is_none(&self) -> bool {
        matches!(self, Filter::None)
    }

    /// A short human-readable form for the filter bar.
    pub fn display(&self) -> String {
        match self {
            Filter::None => String::new(),
            Filter::Raw(sql) => sql.clone(),
            Filter::Match(pairs) => pairs
                .iter()
                .map(|(c, v)| format!("{c} = {}", quote_literal_for_display(v)))
                .collect::<Vec<_>>()
                .join(" AND "),
        }
    }

    /// Text typed by the user: empty means no filter.
    pub fn from_text(text: &str) -> Filter {
        let t = text.trim();
        if t.is_empty() { Filter::None } else { Filter::Raw(t.to_string()) }
    }
}

/// Display-only quoting (`42` stays bare, text gets single quotes). Never used to build SQL.
fn quote_literal_for_display(v: &str) -> String {
    if !v.is_empty() && v.chars().all(|c| c.is_ascii_digit() || c == '-' || c == '.') {
        v.to_string()
    } else {
        format!("'{}'", v.replace('\'', "''"))
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Query {
    pub sort: Option<Sort>,
    pub filter: Filter,
}

/// A generated statement plus the text parameters that follow `$1` (limit) and `$2` (offset).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuiltQuery {
    pub sql: String,
    pub text_params: Vec<String>,
    /// Character range of the user's raw filter inside `sql`, for mapping error positions back.
    pub filter_span: Option<std::ops::Range<usize>>,
}

fn qualified_col(name: &str) -> String {
    format!("{}.{}", quote_ident(TABLE_ALIAS), quote_ident(name))
}

/// The select-list entry for a column: one `text` expression for small types, or a guarded pair
/// (`value-or-NULL`, `stored size`) for types that can hold large values. `CASE` short-circuits, so
/// the cast of an over-limit value is never evaluated.
fn select_expr(c: &Column) -> String {
    let col = qualified_col(&c.name);
    if c.is_large_capable() {
        format!(
            "CASE WHEN pg_column_size({col}) > {INLINE_STORED_LIMIT} THEN NULL ELSE {col}::text END, \
             pg_column_size({col})"
        )
    } else {
        format!("{col}::text")
    }
}

/// Decodes one row produced by [`select_expr`] entries, in column order.
fn decode_row(row: &tokio_postgres::Row, columns: &[Column]) -> Vec<Cell> {
    let mut at = 0;
    columns
        .iter()
        .map(|c| {
            let text: Option<String> = row.get(at);
            if !c.is_large_capable() {
                at += 1;
                return text.map_or(Cell::Null, Cell::Text);
            }
            let stored: Option<i32> = row.get(at + 1);
            at += 2;
            match (text, stored) {
                (Some(t), _) if t.len() <= MAX_INLINE_TEXT_BYTES => Cell::Text(t),
                (Some(t), stored) => Cell::Large { stored_bytes: stored.map_or(t.len() as i64, i64::from) },
                (None, Some(bytes)) => Cell::Large { stored_bytes: i64::from(bytes) },
                (None, None) => Cell::Null,
            }
        })
        .collect()
}

/// Builds ` WHERE ...` (or nothing). `first_param` is the number of the first text parameter.
fn where_clause(
    columns: &[Column],
    filter: &Filter,
    first_param: usize,
    prefix_len: usize,
) -> Result<(String, Vec<String>, Option<std::ops::Range<usize>>), UserFacingError> {
    match filter {
        Filter::None => Ok((String::new(), Vec::new(), None)),
        Filter::Raw(sql) => {
            // Newlines around the expression stop a trailing `-- comment` from eating the `)`.
            let head = " WHERE (\n";
            let start = prefix_len + head.chars().count();
            let span = start..start + sql.chars().count();
            Ok((format!("{head}{sql}\n)"), Vec::new(), Some(span)))
        }
        Filter::Match(pairs) => {
            let mut parts = Vec::new();
            let mut params = Vec::new();
            for (i, (name, value)) in pairs.iter().enumerate() {
                let col = columns.iter().find(|c| &c.name == name).ok_or_else(|| {
                    UserFacingError::config(
                        "Unknown column",
                        format!("The filter refers to column \"{name}\", which this table does not have."),
                    )
                })?;
                parts.push(format!(
                    "{} = CAST(${}::text AS {})",
                    qualified_col(name),
                    first_param + i,
                    col.type_name
                ));
                params.push(value.clone());
            }
            Ok((format!(" WHERE {}", parts.join(" AND ")), params, None))
        }
    }
}

/// Builds the paging query. Ordered by the requested sort, then by primary key, so pages are
/// stable even when the sort column has duplicates.
pub fn page_query(
    schema: &str,
    table: &str,
    columns: &[Column],
    query: &Query,
) -> Result<BuiltQuery, UserFacingError> {
    let select_list = columns.iter().map(select_expr).collect::<Vec<_>>().join(", ");
    let from = format!(
        "SELECT {select_list} FROM {} AS {}",
        quote_qualified(schema, table),
        quote_ident(TABLE_ALIAS)
    );
    let (where_sql, text_params, filter_span) =
        where_clause(columns, &query.filter, 3, from.chars().count())?;

    let mut order: Vec<String> = Vec::new();
    if let Some(sort) = &query.sort {
        if !columns.iter().any(|c| c.name == sort.column) {
            return Err(UserFacingError::config(
                "Unknown column",
                format!("Cannot sort by \"{}\": this table has no such column.", sort.column),
            ));
        }
        order.push(format!(
            "{}{}",
            qualified_col(&sort.column),
            if sort.descending { " DESC" } else { "" }
        ));
    }
    for c in columns.iter().filter(|c| c.is_primary_key) {
        if query.sort.as_ref().is_none_or(|s| s.column != c.name) {
            order.push(qualified_col(&c.name));
        }
    }
    let order_sql = if order.is_empty() {
        String::new()
    } else {
        format!(" ORDER BY {}", order.join(", "))
    };
    Ok(BuiltQuery {
        sql: format!("{from}{where_sql}{order_sql} LIMIT $1 OFFSET $2"),
        text_params,
        filter_span,
    })
}

/// A syntax error's `POSITION` counts characters into the whole statement; make it relative to
/// what the user typed in the filter bar, or drop it if it points at our own SQL.
fn relocate_position(mut err: UserFacingError, span: Option<&std::ops::Range<usize>>) -> UserFacingError {
    err.position = match (err.position, span) {
        (Some(p), Some(span)) => {
            let p = p as usize; // 1-based
            (p > span.start && p <= span.end + 1).then(|| (p - span.start) as u32)
        }
        _ => None,
    };
    err
}

fn bind<'a>(
    limit: &'a i64,
    offset: &'a i64,
    text: &'a [String],
) -> Vec<&'a (dyn tokio_postgres::types::ToSql + Sync)> {
    let mut params: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = vec![limit, offset];
    params.extend(text.iter().map(|s| s as &(dyn tokio_postgres::types::ToSql + Sync)));
    params
}

pub async fn fetch_page(
    session: &Session,
    schema: &str,
    table: &str,
    columns: &[Column],
    query: &Query,
    offset: usize,
    limit: usize,
) -> Result<TablePage, UserFacingError> {
    let target = session.info().endpoint.clone();
    let built = page_query(schema, table, columns, query)?;
    // One extra row tells us whether another page exists without a separate count query.
    let fetch = i64::try_from(limit + 1).unwrap_or(i64::MAX);
    let skip = i64::try_from(offset).unwrap_or(i64::MAX);
    let params = bind(&fetch, &skip, &built.text_params);
    let mut rows = session
        .client()
        .query(&built.sql, &params)
        .await
        .map_err(|e| relocate_position(UserFacingError::from_pg(&e, Some(&target)), built.filter_span.as_ref()))?;
    let has_more = rows.len() > limit;
    rows.truncate(limit);
    let rows = rows.iter().map(|r| decode_row(r, columns)).collect();
    Ok(TablePage {
        columns: columns.to_vec(),
        rows,
        offset,
        has_more,
    })
}

/// Exact number of rows matching `filter`. Can be slow on big tables: run it on its own
/// connection so it can be cancelled without touching anything else.
pub async fn count_rows(
    session: &Session,
    schema: &str,
    table: &str,
    columns: &[Column],
    filter: &Filter,
) -> Result<i64, UserFacingError> {
    let target = session.info().endpoint.clone();
    let head = format!(
        "SELECT count(*) FROM {} AS {}",
        quote_qualified(schema, table),
        quote_ident(TABLE_ALIAS)
    );
    // Here the first text parameter is $1 (no limit/offset).
    let (where_sql, text_params, span) = where_clause(columns, filter, 1, head.chars().count())?;
    let params: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = text_params
        .iter()
        .map(|s| s as &(dyn tokio_postgres::types::ToSql + Sync))
        .collect();
    let row = session
        .client()
        .query_one(&format!("{head}{where_sql}"), &params)
        .await
        .map_err(|e| relocate_position(UserFacingError::from_pg(&e, Some(&target)), span.as_ref()))?;
    Ok(row.get(0))
}

/// Result of loading one value on demand.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CellFetch {
    Full(String),
    /// The text form is larger than the cap; nothing beyond the cap was transferred.
    TooLarge { total_bytes: i64 },
    Null,
    /// No row matches the key any more.
    RowMissing,
}

/// Loads a single value by primary key, transferring at most `max_bytes` (plus one byte to detect
/// overflow). The server still produces the full text once (a single evaluation, in a subselect),
/// so run this on its own connection with a statement timeout and offer Cancel.
pub async fn fetch_cell(
    session: &Session,
    schema: &str,
    table: &str,
    columns: &[Column],
    key: &[(String, String)],
    column: &str,
    max_bytes: usize,
) -> Result<CellFetch, UserFacingError> {
    let target = session.info().endpoint.clone();
    if !columns.iter().any(|c| c.name == column) {
        return Err(UserFacingError::config(
            "Unknown column",
            format!("This table has no column \"{column}\"."),
        ));
    }
    let head = format!(
        "SELECT substr(v, 1, $1), octet_length(v) FROM (SELECT {}::text AS v FROM {} AS {}",
        qualified_col(column),
        quote_qualified(schema, table),
        quote_ident(TABLE_ALIAS)
    );
    // Text parameters start at $2 (after the length cap).
    let filter = Filter::Match(key.to_vec());
    let (where_sql, text_params, _) = where_clause(columns, &filter, 2, head.chars().count())?;
    let sql = format!("{head}{where_sql}) x");
    let cap = i32::try_from(max_bytes + 1).unwrap_or(i32::MAX);
    let mut params: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = vec![&cap];
    params.extend(text_params.iter().map(|s| s as &(dyn tokio_postgres::types::ToSql + Sync)));
    let rows = session
        .client()
        .query(&sql, &params)
        .await
        .map_err(|e| UserFacingError::from_pg(&e, Some(&target)))?;
    let Some(row) = rows.first() else { return Ok(CellFetch::RowMissing) };
    let prefix: Option<String> = row.get(0);
    let total: Option<i32> = row.get(1);
    let (Some(prefix), Some(total)) = (prefix, total) else { return Ok(CellFetch::Null) };
    // `substr` counts characters and `octet_length` bytes; the byte length is what is compared.
    if i64::from(total) > max_bytes as i64 {
        Ok(CellFetch::TooLarge { total_bytes: i64::from(total) })
    } else {
        Ok(CellFetch::Full(prefix))
    }
}

/// The page that contains the last row, given an exact total.
pub fn last_page_offset(total: i64, page_size: usize) -> usize {
    if total <= 0 || page_size == 0 {
        return 0;
    }
    let total = total as usize;
    ((total - 1) / page_size) * page_size
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, ty: &str, pk: bool) -> Column {
        Column { name: name.into(), type_name: ty.into(), is_primary_key: pk, ..Default::default() }
    }

    fn q(sort: Option<(&str, bool)>, filter: Filter) -> Query {
        Query {
            sort: sort.map(|(c, d)| Sort { column: c.into(), descending: d }),
            filter,
        }
    }

    #[test]
    fn default_query_casts_quotes_and_orders_by_pk() {
        let cols = [col("order_id", "bigint", true), col("we\"ird", "integer", false), col("qty", "integer", true)];
        let b = page_query("shop", "order items", &cols, &Query::default()).unwrap();
        assert_eq!(
            b.sql,
            "SELECT \"pgb_t\".\"order_id\"::text, \"pgb_t\".\"we\"\"ird\"::text, \"pgb_t\".\"qty\"::text \
             FROM \"shop\".\"order items\" AS \"pgb_t\" \
             ORDER BY \"pgb_t\".\"order_id\", \"pgb_t\".\"qty\" LIMIT $1 OFFSET $2"
        );
        assert!(b.text_params.is_empty() && b.filter_span.is_none());
    }

    #[test]
    fn large_capable_columns_get_the_size_guard_and_small_ones_do_not() {
        let cols = [col("id", "bigint", true), col("doc", "jsonb", false)];
        let sql = page_query("s", "t", &cols, &Query::default()).unwrap().sql;
        assert!(sql.contains("\"pgb_t\".\"id\"::text, CASE WHEN pg_column_size(\"pgb_t\".\"doc\") > 8192 THEN NULL ELSE \"pgb_t\".\"doc\"::text END, pg_column_size(\"pgb_t\".\"doc\") FROM"), "{sql}");
        assert_eq!(sql.matches("pg_column_size").count(), 2, "only the jsonb column is guarded: {sql}");
    }

    #[test]
    fn bounded_type_classification() {
        for t in ["integer", "bigint", "numeric(10,2)", "boolean", "uuid", "date", "timestamp with time zone",
                  "timestamp(3) without time zone", "time without time zone", "interval", "character(3)", "inet"] {
            assert!(is_bounded_type(t), "{t} should be bounded");
        }
        for t in ["text", "jsonb", "json", "bytea", "xml", "character varying(255)", "integer[]", "text[]",
                  "int4range", "shop.order_status", "hstore"] {
            assert!(!is_bounded_type(t), "{t} may be large");
        }
    }

    #[test]
    fn writability_follows_identity_and_generation() {
        let mut c = col("a", "integer", false);
        assert!(c.is_writable());
        c.identity = Identity::Always;
        assert!(!c.is_writable());
        c.identity = Identity::ByDefault;
        assert!(c.is_writable());
        c.generated = true;
        assert!(!c.is_writable());
    }

    #[test]
    fn no_pk_and_no_sort_means_no_order_by() {
        let b = page_query("shop", "audit_log", &[col("at", "timestamptz", false)], &Query::default()).unwrap();
        assert!(!b.sql.contains("ORDER BY"));
    }

    #[test]
    fn sort_comes_first_then_pk_tiebreak_without_duplicating_the_pk() {
        let cols = [col("id", "bigint", true), col("email", "text", false)];
        let b = page_query("s", "t", &cols, &q(Some(("email", true)), Filter::None)).unwrap();
        assert!(b.sql.ends_with("ORDER BY \"pgb_t\".\"email\" DESC, \"pgb_t\".\"id\" LIMIT $1 OFFSET $2"), "{}", b.sql);
        let b = page_query("s", "t", &cols, &q(Some(("id", false)), Filter::None)).unwrap();
        assert_eq!(b.sql.matches("\"pgb_t\".\"id\"").count(), 2, "select list + one ORDER BY entry: {}", b.sql);
    }

    #[test]
    fn sorting_by_an_unknown_column_is_an_error_not_sql() {
        let cols = [col("id", "bigint", true)];
        let err = page_query("s", "t", &cols, &q(Some(("x\"; DROP TABLE t; --", false)), Filter::None)).unwrap_err();
        assert_eq!(err.kind, ErrorKind::Config);
    }

    #[test]
    fn raw_filter_is_wrapped_on_its_own_lines_and_its_span_recorded() {
        let cols = [col("price", "numeric", false)];
        let b = page_query("s", "t", &cols, &q(None, Filter::Raw("price > 10 -- cheap".into()))).unwrap();
        assert!(b.sql.contains(" WHERE (\nprice > 10 -- cheap\n)"), "a trailing comment must not swallow the paren: {}", b.sql);
        let span = b.filter_span.unwrap();
        let chars: Vec<char> = b.sql.chars().collect();
        assert_eq!(chars[span].iter().collect::<String>(), "price > 10 -- cheap");
    }

    #[test]
    fn match_filter_uses_bound_params_cast_to_the_column_type() {
        let cols = [col("customer_id", "bigint", false), col("sku", "character varying(20)", false)];
        let f = Filter::Match(vec![("customer_id".into(), "7".into()), ("sku".into(), "A'; DROP".into())]);
        let b = page_query("s", "t", &cols, &q(None, f)).unwrap();
        assert!(b.sql.contains(
            "WHERE \"pgb_t\".\"customer_id\" = CAST($3::text AS bigint) AND \"pgb_t\".\"sku\" = CAST($4::text AS character varying(20))"
        ), "{}", b.sql);
        assert_eq!(b.text_params, ["7", "A'; DROP"]);
        assert!(!b.sql.contains("DROP"), "values never appear in the SQL text");
    }

    #[test]
    fn match_filter_on_an_unknown_column_is_rejected() {
        let err = page_query("s", "t", &[col("id", "bigint", true)], &q(None, Filter::Match(vec![("nope".into(), "1".into())]))).unwrap_err();
        assert_eq!(err.kind, ErrorKind::Config);
    }

    #[test]
    fn filter_text_and_display() {
        assert_eq!(Filter::from_text("   "), Filter::None);
        assert_eq!(Filter::from_text(" a = 1 "), Filter::Raw("a = 1".into()));
        let m = Filter::Match(vec![("customer_id".into(), "42".into()), ("name".into(), "O'Neil".into())]);
        assert_eq!(m.display(), "customer_id = 42 AND name = 'O''Neil'");
        assert_eq!(Filter::None.display(), "");
    }

    #[test]
    fn error_positions_are_made_relative_to_the_filter_text() {
        let span = 20..35; // filter occupies chars 20..35 of the statement
        let mk = |p| UserFacingError { position: Some(p), ..UserFacingError::config("t", "d") };
        assert_eq!(relocate_position(mk(21), Some(&span)).position, Some(1), "first char of the filter");
        assert_eq!(relocate_position(mk(25), Some(&span)).position, Some(5));
        assert_eq!(relocate_position(mk(5), Some(&span)).position, None, "points into our own SQL");
        assert_eq!(relocate_position(mk(99), Some(&span)).position, None);
        assert_eq!(relocate_position(mk(3), None).position, None);
    }

    #[test]
    fn last_page_math() {
        assert_eq!(last_page_offset(2500, 500), 2000);
        assert_eq!(last_page_offset(2501, 500), 2500);
        assert_eq!(last_page_offset(500, 500), 0);
        assert_eq!(last_page_offset(1, 500), 0);
        assert_eq!(last_page_offset(0, 500), 0);
    }
}
