\connect pgb

CREATE SCHEMA shop;
CREATE SCHEMA secret;

CREATE TYPE shop.order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE TABLE shop.customers (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email       text NOT NULL UNIQUE,
    full_name   text,
    tags        text[] NOT NULL DEFAULT '{}',
    profile     jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.customers IS 'People who buy things';

CREATE TABLE shop.products (
    sku         text PRIMARY KEY,
    name        text NOT NULL,
    price       numeric(10,2) NOT NULL CHECK (price >= 0),
    dims        int4range,
    photo       bytea,
    in_stock    boolean NOT NULL DEFAULT true
);

CREATE TABLE shop.orders (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  bigint NOT NULL REFERENCES shop.customers(id) ON DELETE CASCADE,
    status       shop.order_status NOT NULL DEFAULT 'pending',
    placed_at    timestamptz NOT NULL DEFAULT now(),
    total        numeric(12,2) GENERATED ALWAYS AS (0) STORED
);
CREATE INDEX orders_customer_idx ON shop.orders (customer_id);
CREATE INDEX orders_open_idx ON shop.orders (placed_at) WHERE status IN ('pending', 'paid');

-- composite primary key
CREATE TABLE shop.order_items (
    order_id  bigint NOT NULL REFERENCES shop.orders(id) ON DELETE CASCADE,
    sku       text   NOT NULL REFERENCES shop.products(sku),
    qty       int    NOT NULL CHECK (qty > 0),
    PRIMARY KEY (order_id, sku)
);

-- no primary key: must open read-only (or via ctid opt-in)
CREATE TABLE shop.audit_log (
    at      timestamptz DEFAULT now(),
    message text
);

CREATE VIEW shop.open_orders AS SELECT * FROM shop.orders WHERE status IN ('pending', 'paid');
CREATE MATERIALIZED VIEW shop.daily_orders AS
    SELECT date_trunc('day', placed_at) AS day, count(*) AS n FROM shop.orders GROUP BY 1;

CREATE TABLE shop.events (
    id bigint GENERATED ALWAYS AS IDENTITY,
    at timestamptz NOT NULL,
    body text,
    PRIMARY KEY (id, at)
) PARTITION BY RANGE (at);
CREATE TABLE shop.events_2026 PARTITION OF shop.events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

CREATE TABLE secret.tokens (id serial PRIMARY KEY, token text NOT NULL);
INSERT INTO secret.tokens (token) VALUES ('do-not-read');

INSERT INTO shop.customers (email, full_name, tags, profile)
SELECT 'user' || g || '@example.com', 'User ' || g, ARRAY['t' || (g % 3)],
       jsonb_build_object('n', g, 'vip', g % 10 = 0)
FROM generate_series(1, 2500) g;
INSERT INTO shop.products VALUES ('A-1', 'Widget', 9.99, '[1,10)', '\xdeadbeef', true),
                                 ('B-2', 'Gadget', 24.50, NULL, NULL, false);
INSERT INTO shop.orders (customer_id, status) SELECT (g % 2500) + 1, 'paid' FROM generate_series(1, 5000) g;
INSERT INTO shop.order_items SELECT id, 'A-1', 1 FROM shop.orders;
INSERT INTO shop.audit_log (message) VALUES ('first'), ('second');
REFRESH MATERIALIZED VIEW shop.daily_orders;

-- pgb_readonly: can read everything in shop, cannot write, cannot see secret
GRANT USAGE ON SCHEMA shop TO pgb_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA shop TO pgb_readonly;
-- pgb_restricted: connects, but has USAGE on nothing (and no CONNECT beyond default)
REVOKE ALL ON SCHEMA secret FROM PUBLIC;

-- Large values: one ~30 MB jsonb (about 1 MB stored, it compresses well), a 1 MB text, and small neighbours.
CREATE TABLE shop.documents (
    id      int PRIMARY KEY,
    title   text NOT NULL,
    small   jsonb,
    big     jsonb,
    body    text
);
INSERT INTO shop.documents VALUES
  (1, 'Huge export', '{"kind": "export"}',
      (SELECT jsonb_build_object('items', jsonb_agg(jsonb_build_object('i', g, 'pad', repeat('x', 120)))) FROM generate_series(1, 200000) g),
      repeat('lorem ipsum ', 100000)),
  (2, 'Small doc', '{"kind": "note", "tags": ["a", "b"]}', '{"tiny": true}', 'a short body'),
  (3, 'Empty doc', NULL, NULL, NULL);
GRANT SELECT ON shop.documents TO pgb_readonly;
